spring.application.name=demo

server.address=0.0.0.0
server.port=${PORT:8080}

# In Render, set SPRING_MONGODB_URI and SPRING_MONGODB_DATABASE as environment variables.
spring.mongodb.uri=mongodb://localhost:27017/Barcel
spring.mongodb.database=Barcel
