spring.application.name=demo
spring.mongodb.uri=mongodb+srv://Pastrana:2626@cluster1.zfokr9u.mongodb.net/?appName=Cluster1
spring.mongodb.database=Barcel
#spring.application.name=demo
#spring.mongodb.host=localhost
#spring.mongodb.port=27017
#spring.mongodb.database=Barcel
#spring.mongodb.username=mazapan
#spring.mongodb.password=271147
#spring.mongodb.authentication-database=admin
